apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image:  rupeshpanwar/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-cluserip-srv
spec:
  selector: 
    app: posts
  ports:
  - name:  posts
    port:  4000
    protocol: TCP
    targetPort: 4000
